### ISSUE TITLE
Arch installation

### ISSUE THREAD

**Issue by SirSharanChakradhar** [fauzie811/Breeze10#1]
Hi,

Sorry for newbie wishes !
Can you please specify installations instructions for Arch Linux too? 

Tx.

**Comment by mmetak** [comment]
```bash

pkgname=breeze10-git
_gitname=Breeze10
pkgver=r7.7c5835d
pkgrel=1
pkgdesc='Breeze10 is a fork of KDE Breeze decoration with windows 10 look'
arch=('x86_64')
url='https://github.com/fauzie811/Breeze10'
license=('GPL3')
depends=('plasma-desktop')
makedepends=('git' 'extra-cmake-modules')
provides=("${pkgname%-*}")
conflicts=("${pkgname%-*}")
source=("git+${url}.git")
sha256sums=('SKIP')

pkgver() {
   cd ${srcdir}/${_gitname}
   printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
}

build() {
   cd ${srcdir}/${_gitname}
   mkdir build && cd build
   cmake .. \
            -DCMAKE_INSTALL_PREFIX=/usr \
            -DCMAKE_BUILD_TYPE=Release \
            -DKDE_INSTALL_LIBDIR=lib \
            -DBUILD_TESTING=OFF \
            -DKDE_INSTALL_USE_QT_SYS_PATHS=ON
   make
}

package() {
   make -C ${srcdir}/${_gitname}/build DESTDIR="$pkgdir" install
}
```

**Comment by fauzie811** [comment]
@mmetak Thank you for your help. I couldn't help because I don't use Arch.

**Comment by SirSharanChakradhar** [comment]
Thank you @mmetak !! Should I need to create this as sh file and then run it?

**Comment by mmetak** [comment]
@fauzie811 No problem, I just quickly modified the existing `PKGBUILD` file.
@SirSharanChakradhar Save that as a `PKGBUILD` file somewhere, cd to that dir and build the package with `makepkg -is`.

**Comment by francoism90** [comment]
@mmetak Thanks for your example, I have uploaded a PKG in AUR (`yay -S breeze10-kde-git`):
https://aur.archlinux.org/packages/breeze10-kde-git/

Still doubts if all deps are included, please let me know if they are missing. :)
