### ISSUE TITLE
Bolder outline around windows

### ISSUE THREAD

**Issue by ripefig** [fauzie811/Breeze10#2]
I would suggest a bolder outline around windows to give them a more complete look and have greater conformity with windows 10.

![image](https://user-images.githubusercontent.com/45201036/61825665-7ccb2d00-ae69-11e9-8157-ec6a5ae2b522.png)

It may also be a good idea to have the active window outline be significantly bolder than the inactive one, to better distinguish the active window - especially in tiled contexts.

**Comment by fauzie811** [comment]
Done.

![Screenshot_20190725_195311](https://user-images.githubusercontent.com/318095/61876170-7d6dcd00-af16-11e9-8291-84027368eaf0.png)

It currently uses a darker shade of the titlebar color.

**Comment by mmetak** [comment]
@fauzie811 Is that your new qt style in that screenshot? If it is please publish it. ;-)
I've been looking something like this for a long time.

**Comment by fauzie811** [comment]
@mmetak I'm using QtCurve.

[Win10.qtcurve](https://gist.github.com/fauzie811/43d0773888d1df1bcb0058d5e22e7d90)
