### ISSUE TITLE
Building errors

### ISSUE THREAD

**Issue by testbughub** [fauzie811/Breeze10#3]
Hi!

I've been trying to build  this with the instructions given, but after a few errors of missing packages that I installed and got through, I have now stalled. I just can't figure out what's missing. I may just be missing something obvious.

But here is the error I get when trying cmake:
https://pastebin.com/mcLrNqV7

Logs:
https://pastebin.com/ZtENCEDn
https://pastebin.com/hbLgvtZT

Any help would be much appreciated!

**Comment by fauzie811** [comment]
I've added Dependencies section in the ReadMe. Install them and it should fix your problem.

**Comment by testbughub** [comment]
Ah perfect, I was wondering what was missing.
Thank you!
